---
version: '3'
services:
  devsolux:
    image: ghcr.io/devsolux/analytics:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://devsolux:devsolux@db:5432/devsolux
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: devsolux
      POSTGRES_USER: devsolux
      POSTGRES_PASSWORD: devsolux
    volumes:
      - devsolux-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  devsolux-db-data:
